---
abstract: 'Create PDF invoices according to the Swiss ESR standard'
author:
  - 'Tobias Oetiker <tobi@oetiker.ch>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-Payment-SwissESR
no_index:
  directory:
    - t
    - inc
    - t
    - example
    - setup
requires:
  Mojolicious: 3.0
  perl: 5.010001
resources:
  bugtracker: https://github.com/oetiker/business-payment-swissesr/issues
  license: http://opensource.org/licenses/GPL-3.0
  repository: https://github.com/oetiker/business-payment-swissesr
version: v0.7.0
